version: '3.8'
services:
 app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: instituto-jef
    image: instituto-jef
    ports:
      - "3000:3000"
    networks:
      - instituto-jef
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
 db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - instituto-jef
volumes:
 postgres_data:

networks:
 instituto-jef:
    driver: bridge